#+TITLE: Racket solutions to 2017 problems

* General usage

To see solutions for a day's puzzles, run the file with its name:

#+BEGIN_SRC bash
$ racket day01.rkt
First puzzle: 	1390
Second puzzle: 	1232
#+END_SRC

Solutions could be different because of the generated problem inputs.

* Notes
** Structure
All files hold both implementation and tests as separate ~module~ parts. They
are intermixed using the ~module+~ form. The ~test~ module holds ~test-case~
forms, and the ~main~ module holds the puzzle input (sometimes read from an
external TXT file) and calls to *print* the result of ~solve~ procedures for the
first and second puzzles.

All procedures to solve the puzzles are created outside these two modules.

#+BEGIN_SRC racket
#lang racket/base

(module+ test
  (require rackunit))

(module+ main
  (printf "First: ~a" (solve-first)))

;; procedures

;; more tests

(module+ main
  (printf "Second: ~a" (solve-second)))
#+END_SRC

** Lessons learned

- Day 01: circle list, number->digits
- Day 02: parse lines, words
- Day 03: manhattan distance, spiral grid
- Day 04: anagrams
- Day 05: -
- Day 06: overwrite vectors
- Day 07: trees
- Day 08: parse "machine instructions"
- Day 09: use a state machine to parse expressions
- Day 10: hash function, circular buffer
- Day 11: hexagonal grid
- Day 12: depth-first search, find subgraphs graph
